#  This file get yoi the secrets which you want

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.awsSecrets.secretProviderClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.awsSecrets.region | quote }}
    usePodIdentity: "true"
    objects: |
      - objectName: {{ .Values.awsSecrets.secretArn | quote }}
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
  secretObjects:
    - secretName: {{ .Values.database.kubernetesSecretName }}
      type: Opaque
      data:
        - objectName: "DB_USERNAME"
          key: "DB_USERNAME"
        - objectName: "DB_PASSWORD"
          key: "DB_PASSWORD"
