apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  SERVER_PORT: "{{ .Values.config.serverPort }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  DB_POOL_MAX: "{{ .Values.config.dbPoolMax }}"
  DB_POOL_MIN_IDLE: "{{ .Values.config.dbPoolMinIdle }}"
  DB_POOL_CONNECTION_TIMEOUT_MS: "{{ .Values.config.dbPoolConnectionTimeoutMs }}"
  DB_POOL_VALIDATION_TIMEOUT_MS: "{{ .Values.config.dbPoolValidationTimeoutMs }}"
  DB_POOL_IDLE_TIMEOUT_MS: "{{ .Values.config.dbPoolIdleTimeoutMs }}"
  DB_POOL_MAX_LIFETIME_MS: "{{ .Values.config.dbPoolMaxLifetimeMs }}"
  SERVER_TOMCAT_MAX_THREADS: "{{ .Values.config.tomcatMaxThreads }}"
  SERVER_TOMCAT_MIN_SPARE_THREADS: "{{ .Values.config.tomcatMinSpareThreads }}"
  SERVER_TOMCAT_ACCEPT_COUNT: "{{ .Values.config.tomcatAcceptCount }}"
  SERVER_TOMCAT_MAX_CONNECTIONS: "{{ .Values.config.tomcatMaxConnections }}"
  OPENAPI_ENABLED: "{{ .Values.config.openapiEnabled }}"
  SWAGGER_ENABLED: "{{ .Values.config.swaggerEnabled }}"
