apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  SERVER_PORT: "{{ .Values.config.serverPort }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  PRODUCT_SERVICE_URL: "{{ .Values.config.productServiceUrl }}"
