apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 9092
    - ports:
        - protocol: TCP
          port: 5672
    - ports:
        - protocol: TCP
          port: 6379
    - ports:
        - protocol: TCP
          port: 1025

    # User Service lookup for order-confirmation recipient
    - ports:
        - protocol: TCP
          port: 8082
