apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
stringData:
  DB_URL: "{{ .Values.database.url }}"
  DB_USERNAME: "{{ .Values.database.username }}"
  DB_PASSWORD: "{{ .Values.database.password }}"
