name: userservice
configMapName: userservice-config
containerPort: 8082
image:
  repository: 663130434910.dkr.ecr.us-east-1.amazonaws.com/boutique-userservice
  tag: "1.0.2"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8082
  targetPort: 8082
serviceAccount:
  name: userservice-sa
  automountServiceAccountToken: false
database:
  url: "jdbc:postgresql://boutique-dev-postgres.ce7qiak863r3.us-east-1.rds.amazonaws.com:5432/user_db"
  kubernetesSecretName: boutique-rds-credentials
config:
  serverPort: "8082"
  corsAllowedOrigins: "https://needystuff.in,http://localhost:4173,http://localhost:5173"
  dbPoolMax: "16"
  dbPoolMinIdle: "2"
  dbPoolConnectionTimeoutMs: "2000"
  dbPoolValidationTimeoutMs: "1000"
  dbPoolIdleTimeoutMs: "60000"
  dbPoolMaxLifetimeMs: "1800000"
  openapiEnabled: "true"
  swaggerEnabled: "true"
revisionHistoryLimit: 5
progressDeadlineSeconds: 600
terminationGracePeriodSeconds: 30
strategy:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 1
resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi
probes:
  path: /actuator/health
  startup:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 18
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3
lifecycle:
  preStopSleepSeconds: 10
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001
topologySpread:
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
autoscaling:
  minReplicas: 2
  maxReplicas: 5
  cpuAverageUtilization: 70
  scaleDownStabilizationSeconds: 300
pdb:
  minAvailable: 1

awsSecrets:
  enabled: true
  secretProviderClassName: boutique-rds-secrets
  mountPath: /mnt/secrets-store
