apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  SERVER_PORT: "{{ .Values.config.serverPort }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  CART_SERVICE_URL: "{{ .Values.config.cartServiceUrl }}"
  ORDER_SERVICE_URL: "{{ .Values.config.orderServiceUrl }}"
  PAYMENT_SERVICE_URL: "{{ .Values.config.paymentServiceUrl }}"
  INVENTORY_SERVICE_URL: "{{ .Values.config.inventoryServiceUrl }}"
  OPENAPI_ENABLED: "{{ .Values.config.openapiEnabled }}"
  SWAGGER_ENABLED: "{{ .Values.config.swaggerEnabled }}"
