apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  SERVER_PORT: "{{ .Values.config.serverPort }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  REDIS_HOST: "{{ .Values.config.redisHost }}"
  REDIS_PORT: "{{ .Values.config.redisPort }}"
  USER_SERVICE_URL: "{{ .Values.config.userServiceUrl }}"
  PRODUCT_SERVICE_URL: "{{ .Values.config.productServiceUrl }}"
  INVENTORY_SERVICE_URL: "{{ .Values.config.inventoryServiceUrl }}"
  CART_TTL: "{{ .Values.config.cartTtl }}"
  CART_MAXIMUM_QUANTITY: "{{ .Values.config.cartMaximumQuantity }}"
  OPENAPI_ENABLED: "{{ .Values.config.openapiEnabled }}"
  SWAGGER_ENABLED: "{{ .Values.config.swaggerEnabled }}"
