apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: boutique
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 6379
    - ports:
        - protocol: TCP
          port: 8080
    - ports:
        - protocol: TCP
          port: 8081
    - ports:
        - protocol: TCP
          port: 8082
